Description: Learn algorithms that predict continuous values.

Algorithms:
- Linear Regression
- Polynomial Regression
- Ridge and Lasso Regression (regularization)
- Decision Trees for Regression
- Random Forest Regression
- Gradient Boosting (XGBoost, LightGBM)

Hands-on Projects:

- House Price Prediction: Predict housing prices using multiple regression techniques
- Stock Price Forecasting: Build a model to predict stock trends
- Salary Prediction: Estimate salaries based on experience and skills

Key Skills: Feature engineering, handling outliers, model comparison

## 1. House Price Prediction

In [17]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True)

df = data.frame

display(df.head())

   MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0  8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1  8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2  7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3  5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4  3.8462      52.0  6.281853  ...     37.85    -122.25        3.422

[5 rows x 9 columns]

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

print(model.score(X_test, y_test))

0.611866567201007

In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

model = LinearRegression()

model.fit(X_poly, y)

LinearRegression()

In [20]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)

RandomForestRegressor()

In [21]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=1.0)

model.fit(X_train, y_train)

Ridge()

In [22]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=0.1)

model.fit(X_train, y_train)

Lasso(alpha=0.1)

In [23]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()

model.fit(X_train, y_train)

DecisionTreeRegressor()

In [24]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()

model.fit(X_train, y_train)

GradientBoostingRegressor()

In [25]:
models = {
    "Linear": LinearRegression(),
    "Random Forest": RandomForestRegressor(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "Decision Tree": DecisionTreeRegressor(),
    "Gradient Boosting": GradientBoostingRegressor()
}

for name, model in models.items():

    model.fit(X_train, y_train)

    print(name, model.score(X_test, y_test))

Linear 0.611866567201007
Random Forest 0.8091498721102817
Ridge 0.6118632098524783
Lasso 0.2970447658992953
Decision Tree 0.5930346917394458
Gradient Boosting 0.7919799901730322

## 2. Stock Price Prediction

In [26]:
import pandas as pd

df = pd.read_csv("p01_2_stocks.csv")

df["Date"] = pd.to_datetime(df["Date"])

display(df.head())

df = df.drop("CloseUSD", axis=1)

  Index       Date         Open  ...    Adj Close  Volume    CloseUSD
0   HSI 1986-12-31  2568.300049  ...  2568.300049     0.0  333.879006
1   HSI 1987-01-02  2540.100098  ...  2540.100098     0.0  330.213013
2   HSI 1987-01-05  2552.399902  ...  2552.399902     0.0  331.811987
3   HSI 1987-01-06  2583.899902  ...  2583.899902     0.0  335.906987
4   HSI 1987-01-07  2607.100098  ...  2607.100098     0.0  338.923013

[5 rows x 9 columns]

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import pandas as pd

df = pd.read_csv('p01_2_stocks.csv')

X = df[["Open", "High", "Low", "Adj Close", "Volume"]]
y = df["Close"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(model.score(X_test_scaled, y_test))

print(y_pred[:5])

comparison = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})

display(comparison)

0.9999999832314929
[12868.07497446  1574.4931648   2887.28435215  9565.86642786
 23331.95773995]

             Actual     Predicted
72981  12868.200200  12868.074974
66841   1578.199951   1574.493165
789     2887.000000   2887.284352
1952    9565.700195   9565.866428
54414  23331.839840  23331.957740
...             ...           ...
58875    899.750000    900.050650
61507   3088.169922   3088.404255
21745  13102.030270  13102.186384
71747   7688.700195   7688.792632
1463    5986.700195   5986.944477

[20845 rows x 2 columns]

## 3. Salary Prediction

In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

model = Ridge(alpha=0.1)

df = pd.read_csv('p01_3_salary.csv')
df.head()

            job_title  experience_years  ... certifications  salary
0         AI Engineer                10  ...              2  109413
1        Data Analyst                 5  ...              0   93764
2  Frontend Developer                18  ...              1  148123
3    Business Analyst                19  ...              0  189123
4     Product Manager                15  ...              0  165069

[5 rows x 10 columns]

In [40]:
X = df[['experience_years', 'skills_count', 'certifications']]
y = df['salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [41]:
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print(model.score(X_test_scaled, y_test))

comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
display(comparison)

0.2098894885526511

        Actual      Predicted
38683   164009  146619.616369
64939    79594  138616.307439
3954     74090  142822.099160
120374  177193  141871.060323
172861  120012  128233.031635
...        ...            ...
179545  136275  148348.266053
222647  168515  150605.120815
171823  176232  158792.960387
135782  152933  162901.576944
208380  116585  112012.764640

[50000 rows x 2 columns]